/* prism.h - PRISM ISA decode tables (AUTO-GENERATED by obfuscate.py). */
#ifndef PRISM_H
#define PRISM_H

#include <stdint.h>

/* ---- field extraction: canonical field <- its permuted PRISM offset ---- */
#define PRISM_OP(w) (((w) >> 11) & 0x3f)
#define PRISM_RS(w) (((w) >> 22) & 0x1f)
#define PRISM_RT(w) (((w) >> 6) & 0x1f)
#define PRISM_RD(w) (((w) >> 17) & 0x1f)
#define PRISM_SA(w) (((w) >> 27) & 0x1f)
#define PRISM_FN(w) (((w) >> 0) & 0x3f)

/* Canonical immediate/target reassembled from the scattered field values:
 *   imm    = rd:sh:fn  (canonical bits 15..0)
 *   target = rs:rt:rd:sh:fn  (canonical bits 25..0) */
#define PRISM_IMM(w) ((PRISM_RD(w) << 11) | (PRISM_SA(w) << 6) | PRISM_FN(w))
#define PRISM_SIMM(w) ((int32_t)(int16_t)PRISM_IMM(w))
#define PRISM_TARGET(w)                                                        \
    ((PRISM_RS(w) << 21) | (PRISM_RT(w) << 16) | PRISM_IMM(w))

/* ---- substituted PRIMARY opcodes (canonical mnemonic -> PRISM value) ---- */
#define PRISM_OP_SPECIAL 0x06 /* MIPS op  0x00 */
#define PRISM_OP_REGIMM 0x01  /* MIPS op  0x01 */
#define PRISM_OP_J 0x03       /* MIPS op  0x02 */
#define PRISM_OP_JAL 0x32     /* MIPS op  0x03 */
#define PRISM_OP_BEQ 0x30     /* MIPS op  0x04 */
#define PRISM_OP_BNE 0x04     /* MIPS op  0x05 */
#define PRISM_OP_BLEZ 0x12    /* MIPS op  0x06 */
#define PRISM_OP_BGTZ 0x33    /* MIPS op  0x07 */
#define PRISM_OP_ADDI 0x25    /* MIPS op  0x08 */
#define PRISM_OP_ADDIU 0x35   /* MIPS op  0x09 */
#define PRISM_OP_SLTI 0x3D    /* MIPS op  0x0A */
#define PRISM_OP_SLTIU 0x37   /* MIPS op  0x0B */
#define PRISM_OP_ANDI 0x0D    /* MIPS op  0x0C */
#define PRISM_OP_ORI 0x1C     /* MIPS op  0x0D */
#define PRISM_OP_XORI 0x0F    /* MIPS op  0x0E */
#define PRISM_OP_LUI 0x1E     /* MIPS op  0x0F */
#define PRISM_OP_COP0 0x1D    /* MIPS op  0x10 */
#define PRISM_OP_COP1 0x39    /* MIPS op  0x11 */
#define PRISM_OP_COP2 0x24    /* MIPS op  0x12 */
#define PRISM_OP_COP3 0x14    /* MIPS op  0x13 */
#define PRISM_OP_LB 0x34      /* MIPS op  0x20 */
#define PRISM_OP_LH 0x2A      /* MIPS op  0x21 */
#define PRISM_OP_LWL 0x0E     /* MIPS op  0x22 */
#define PRISM_OP_LW 0x08      /* MIPS op  0x23 */
#define PRISM_OP_LBU 0x3C     /* MIPS op  0x24 */
#define PRISM_OP_LHU 0x0A     /* MIPS op  0x25 */
#define PRISM_OP_LWR 0x27     /* MIPS op  0x26 */
#define PRISM_OP_SB 0x11      /* MIPS op  0x28 */
#define PRISM_OP_SH 0x31      /* MIPS op  0x29 */
#define PRISM_OP_SWL 0x18     /* MIPS op  0x2A */
#define PRISM_OP_SW 0x21      /* MIPS op  0x2B */
#define PRISM_OP_SWR 0x3E     /* MIPS op  0x2E */

/* ---- substituted SPECIAL funct codes (canonical mnemonic -> PRISM value) ---- */
#define PRISM_FN_SLL 0x3A     /* MIPS funct 0x00 */
#define PRISM_FN_SRL 0x1F     /* MIPS funct 0x02 */
#define PRISM_FN_SRA 0x2D     /* MIPS funct 0x03 */
#define PRISM_FN_SLLV 0x26    /* MIPS funct 0x04 */
#define PRISM_FN_SRLV 0x18    /* MIPS funct 0x06 */
#define PRISM_FN_SRAV 0x19    /* MIPS funct 0x07 */
#define PRISM_FN_JR 0x29      /* MIPS funct 0x08 */
#define PRISM_FN_JALR 0x30    /* MIPS funct 0x09 */
#define PRISM_FN_SYSCALL 0x11 /* MIPS funct 0x0C */
#define PRISM_FN_BREAK 0x02   /* MIPS funct 0x0D */
#define PRISM_FN_MFHI 0x1A    /* MIPS funct 0x10 */
#define PRISM_FN_MTHI 0x22    /* MIPS funct 0x11 */
#define PRISM_FN_MFLO 0x36    /* MIPS funct 0x12 */
#define PRISM_FN_MTLO 0x1E    /* MIPS funct 0x13 */
#define PRISM_FN_MULT 0x08    /* MIPS funct 0x18 */
#define PRISM_FN_MULTU 0x0C   /* MIPS funct 0x19 */
#define PRISM_FN_DIV 0x0B     /* MIPS funct 0x1A */
#define PRISM_FN_DIVU 0x33    /* MIPS funct 0x1B */
#define PRISM_FN_ADD 0x03     /* MIPS funct 0x20 */
#define PRISM_FN_ADDU 0x31    /* MIPS funct 0x21 */
#define PRISM_FN_SUB 0x04     /* MIPS funct 0x22 */
#define PRISM_FN_SUBU 0x1D    /* MIPS funct 0x23 */
#define PRISM_FN_AND 0x32     /* MIPS funct 0x24 */
#define PRISM_FN_OR 0x3B      /* MIPS funct 0x25 */
#define PRISM_FN_XOR 0x37     /* MIPS funct 0x26 */
#define PRISM_FN_NOR 0x17     /* MIPS funct 0x27 */
#define PRISM_FN_SLT 0x10     /* MIPS funct 0x2A */
#define PRISM_FN_SLTU 0x1C    /* MIPS funct 0x2B */

#endif /* PRISM_H */
