#!/usr/bin/env python3
"""bin2c.py - embed a binary blob into a C header as a byte array."""
import argparse
import os


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--symbol", default=None,
                    help="C identifier (default: derived from input filename)")
    args = ap.parse_args()

    sym = args.symbol
    if sym is None:
        sym = os.path.basename(args.input)
        sym = "".join(ch if ch.isalnum() else "_" for ch in sym)
        if sym and sym[0].isdigit():
            sym = "_" + sym

    with open(args.input, "rb") as f:
        data = f.read()

    lines = []
    lines.append("/* Auto-generated by src/tools/bin2c.py. Do not edit. */")
    lines.append(f"/* source: {os.path.basename(args.input)} ({len(data)} bytes) */")
    lines.append("#ifndef BIN2C_%s_H" % sym.upper())
    lines.append("#define BIN2C_%s_H" % sym.upper())
    lines.append("")
    lines.append(f"static const unsigned char {sym}[] = {{")
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + " ".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    lines.append(f"static const unsigned int {sym}_len = {len(data)}u;")
    lines.append("")
    lines.append("#endif")
    lines.append("")

    with open(args.output, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
