#!/usr/bin/env python3
"""prism.py -- PRISM codec (AUTO-GENERATED by obfuscate.py)."""

import struct

SEED = bytes.fromhex("24559a45da23f2cdb3b8c386da9b985d4fcbf1226a64c3fab7bddb80d8aba8ca")

# Canonical MIPS-I field positions (hi, lo), MSB = bit 31.
FIELDS = {
    'op': (31, 26),
    'rs': (25, 21),
    'rt': (20, 16),
    'rd': (15, 11),
    'sh': (10, 6),
    'fn': (5, 0),
}
OP_R = 0x00

BLOCK_ORDER = ['sh', 'rs', 'rd', 'op', 'rt', 'fn']  # MSB->LSB in the PRISM word
OP_BOX = [6, 1, 3, 50, 48, 4, 18, 51, 37, 53, 61, 55, 13, 28, 15, 30, 29, 57, 36, 20, 2, 32, 43, 40, 12, 58, 31, 54, 45, 44, 56, 11, 52, 42, 14, 8, 60, 10, 39, 41, 17, 49, 24, 33, 9, 63, 62, 25, 21, 35, 23, 22, 0, 5, 26, 27, 59, 34, 46, 7, 38, 47, 16, 19]
FN_BOX = [58, 60, 31, 45, 38, 9, 24, 25, 41, 48, 19, 42, 17, 2, 15, 33, 26, 34, 54, 30, 21, 52, 32, 6, 8, 12, 11, 51, 18, 20, 57, 63, 3, 49, 4, 29, 50, 59, 55, 23, 40, 35, 16, 28, 27, 5, 36, 37, 7, 46, 1, 62, 14, 13, 22, 10, 43, 39, 53, 56, 0, 44, 47, 61]
OP_INV = [0] * 64
FN_INV = [0] * 64
for _x, _y in enumerate(OP_BOX): OP_INV[_y] = _x
for _x, _y in enumerate(FN_BOX): FN_INV[_y] = _x


def _perm():
    perm = [0] * 32
    obf_hi = 31
    for name in BLOCK_ORDER:
        hi, lo = FIELDS[name]
        for k in range(hi - lo + 1):
            perm[hi - k] = obf_hi - k
        obf_hi -= (hi - lo + 1)
    return perm


PERM = _perm()
INV_PERM = [0] * 32
for _i, _p in enumerate(PERM): INV_PERM[_p] = _i


def _get(w, hi, lo): return (w >> lo) & ((1 << (hi - lo + 1)) - 1)


def _set(w, hi, lo, v):
    width = hi - lo + 1
    m = ((1 << width) - 1) << lo
    return (w & ~m) | ((v & ((1 << width) - 1)) << lo)


def _permute(w, perm):
    out = 0
    for i in range(32):
        if (w >> i) & 1:
            out |= 1 << perm[i]
    return out & 0xFFFFFFFF


def encode_word(word):
    """MIPS I instruction word -> PRISM instruction word."""
    word &= 0xFFFFFFFF
    op = _get(word, *FIELDS['op'])
    w = _set(word, *FIELDS['op'], OP_BOX[op])
    if op == OP_R:
        w = _set(w, *FIELDS['fn'], FN_BOX[_get(word, *FIELDS['fn'])])
    return _permute(w, PERM)


def decode_word(obf):
    """PRISM instruction word -> MIPS I instruction word."""
    w = _permute(obf & 0xFFFFFFFF, INV_PERM)
    op = OP_INV[_get(w, *FIELDS['op'])]
    w = _set(w, *FIELDS['op'], op)
    if op == OP_R:
        w = _set(w, *FIELDS['fn'], FN_INV[_get(w, *FIELDS['fn'])])
    return w


def encode_bytes(blob):
    """Re-encode a little-endian stream of 4-byte MIPS words to PRISM."""
    if len(blob) % 4:
        raise ValueError("instruction stream must be a multiple of 4 bytes")
    out = bytearray()
    for off in range(0, len(blob), 4):
        (w,) = struct.unpack_from("<I", blob, off)
        out += struct.pack("<I", encode_word(w))
    return bytes(out)

